name: Matrix build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    strategy:
      # ランナーラベルとgenerator指定オプションの組み合わせマトリックス
      matrix:
        target:
          - os: ubuntu-latest
          - os: macos-latest
            generator: '-G "Xcode"'
          - os: windows-latest
            generator: '-G "Visual Studio 17 2022"'
    runs-on: ${{ matrix.target.os }}
    steps:
      # セットアップ
      - uses: actions/checkout@v6
      - uses: microsoft/setup-msbuild@v3
        if: runner.os == 'Windows' # Windowsのときだけsetup-msbuildを実行する

      # CMakeでプロジェクトを作成
      - name: CMake
        run: |
          mkdir build && cd build && cmake ${{ matrix.target.generator }} ..
      # ビルドの実行
      - name: Build
        run: cmake --build build

      # 成果物をアップロード
      - name: Archive app
        env:
          ARCHIVE_PATH: build/bin
        shell: pwsh
        # powershellで成果物ディレクトリを圧縮
        run: Compress-Archive -Path $Env:ARCHIVE_PATH -Destination point.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: point-matrix-${{ runner.os }}
          path: point.zip
